name: materialsautomated-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - dill
  - pandas
  - bokeh
  - ase
  - ase-notebook
  - pythreejs
  - scons
  - tomopy
  - dxchange
  - ipyvolume

